version: "3"
services: 
  my_mysql:
    image: "mysql:latest"
    ports:
      - 52000:3306
    environment:
      MYSQL_ROOT_PASSWORD: ws-123456
    volumes:
       - /service/data/mysqldata:/var/lib/mysql
  my_redis:
    image: "redis:7.0.15"
    environment:
      REDIS_PASSWORD: ws-1234
    ports:
      - 52001:6379
    privileged: true
